### ISSUE TITLE
[TODO] Stylistic issues

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#14]
Collating a running list of stylistic issues that I see as they crop up.

For each notebook that I've created:

- [x] Ensure data loading occurs through `load_xyz()`.
- [x] "Exercise" should not be a header, but bolded font.
- [x] Traceplots should be despined. (Convenience function: `utils.despine_traceplot(traces)`)
- [x] All other plots should be despined. (Convenience function: `utils.despine(ax)`)
- [x] "Discuss" should not be a header, but a bolded font.

Things to harmonize between Hugo's and my notebooks:

- [x] Notebook numbering. I think we should stick to `01-...`, `02-...`, `03-...` etc.
- [ ] Section numbering. I'm hesitant to number things because of maintenance issues, but I see its utility for navigation within a notebook.

Will append to this comment as more things crop up.

**Comment by hugobowne** [comment]
We've discussed why I've numbered sections and are at peace w/ this minimal inconsistency.
